//
//  InAppSDKGatewayError.h
//  InAppSDK
//
//  Created by Senthil Kumar Periyasamy on 10/15/15.
//  Copyright (c) 2015 CyberSource, a Visa Company. All rights reserved.
//

#import "InAppSDKError.h"

//!This enumeration represents different types of the Transaction errors.
typedef enum
{
    INAPPSDK_GATEWAY_ERROR_TYPE_UNKNOWN                                  = 2000,
    INAPPSDK_GATEWAY_ERROR_MISSING_FIELDS,
    INAPPSDK_GATEWAY_ERROR_FIELDS_CONTAINS_INVALID_DATA,
    INAPPSDK_GATEWAY_ERROR_ONLY_PARTIAL_APPROVED,
    INAPPSDK_GATEWAY_ERROR_GENERAL_SYSTEM_FAILURE,
    INAPPSDK_GATEWAY_ERROR_SERVER_TIMEOUT,
    INAPPSDK_GATEWAY_ERROR_SERVICE_DID_NOT_FINISH,
    INAPPSDK_GATEWAY_ERROR_DID_NOT_PASS_AVS,
    INAPPSDK_GATEWAY_ERROR_ISSUING_BANK_HAS_QUESTIONS,
    INAPPSDK_GATEWAY_ERROR_EXPIRED_CARD,
    INAPPSDK_GATEWAY_ERROR_GENERAL_DECLINE,
    INAPPSDK_GATEWAY_ERROR_INSUFFICIENT_FUNDS,
    INAPPSDK_GATEWAY_ERROR_STOLEN_OR_LOST_CARD,
    INAPPSDK_GATEWAY_ERROR_ISSUING_BANK_UNAVAILABLE,
    INAPPSDK_GATEWAY_ERROR_INACTIVE_CARD,
    INAPPSDK_GATEWAY_ERROR_CID_DID_NOT_MATCH,
    INAPPSDK_GATEWAY_ERROR_CREDIT_LIMIT,
    INAPPSDK_GATEWAY_ERROR_INVALID_CVN,
    INAPPSDK_GATEWAY_ERROR_NEGATIVE_FILE,
    INAPPSDK_GATEWAY_ERROR_DID_NOT_PASS_CVN_CHECK,
    INAPPSDK_GATEWAY_ERROR_INVALID_ACCOUNT_NUMBER,
    INAPPSDK_GATEWAY_ERROR_CARD_TYPE_NOT_EXPECTED,
    INAPPSDK_GATEWAY_ERROR_GENERAL_DECLINE_BY_PROCESSOR,
    INAPPSDK_GATEWAY_ERROR_PROBLEM_WITH_INFORMATION,
    INAPPSDK_GATEWAY_ERROR_CAPTURE_AMOUNT_EXCEEDS,
    INAPPSDK_GATEWAY_ERROR_PROCESSOR_FAILURE,
    INAPPSDK_GATEWAY_ERROR_ALREADY_REVERSED,
    INAPPSDK_GATEWAY_ERROR_ALREADY_CAPTURED,
    INAPPSDK_GATEWAY_ERROR_TRANSACTION_AMOUNT_MUST_MATCH_PREVIOUS_AMOUNT,
    INAPPSDK_GATEWAY_ERROR_CARD_TYPE_INVALID,
    INAPPSDK_GATEWAY_ERROR_REQUEST_ID_INVALID,
    INAPPSDK_GATEWAY_ERROR_NO_CORRESPONDING,
    INAPPSDK_GATEWAY_ERROR_TRANSACTION_SETTLED_OR_REVERSED,
    INAPPSDK_GATEWAY_ERROR_NOT_VOIDABLE,
    INAPPSDK_GATEWAY_ERROR_REQUEST_FOR_CAPTURE_THAT_WAS_VOIDED,
    INAPPSDK_GATEWAY_ERROR_TIMEOUT_AT_PAYMENT_PROCESSOR,
    INAPPSDK_GATEWAY_ERROR_STAND_ALONE_CREDITS_NOT_ALLOWED,
    INAPPSDK_GATEWAY_ERROR_NETWORK_CONNECTION,
    INAPPSDK_GATEWAY_ERROR_INVALID_TOKEN,
    
} InAppSDKGatewayErrorType;

@interface InAppSDKGatewayError : InAppSDKError

+ (BOOL) isGatewayErrorCode:(NSInteger)paramErrorCode;


@end
