//
//  InAppSDKHttpConnectionError.h
//  InAppSDK
//
//  Created by Senthil Kumar Periyasamy on 10/14/15.
//  Copyright (c) 2015 CyberSource, a Visa Company. All rights reserved.
//

#import "InAppSDKError.h"

typedef enum
{
    INAPPSDK_HTTP_ERROR_TYPE_NOT_DEFINED = 0,
    INAPPSDK_HTTP_ERROR_TYPE_OK = 200,
    INAPPSDK_HTTP_ERROR_TYPE_CREATED = 201,
    INAPPSDK_HTTP_ERROR_TYPE_ACCEPTED = 202,
    INAPPSDK_HTTP_ERROR_TYPE_BAD_REQUEST = 400,
    INAPPSDK_HTTP_ERROR_TYPE_UNAUTHORIZED = 401,
    INAPPSDK_HTTP_ERROR_TYPE_FORBIDDEN = 403,
    INAPPSDK_HTTP_ERROR_TYPE_NOT_FOUND = 404,
    INAPPSDK_HTTP_ERROR_TYPE_SERVER = 500,
    
    /* CFURL and CFURLConnection Errors */
    INAPPSDK_HTTP_ERROR_TYPE_UNKNOWN   = -998,
    INAPPSDK_HTTP_ERROR_TYPE_CANCELLED = -999,
    INAPPSDK_HTTP_ERROR_TYPE_BADURL    = -1000,
    INAPPSDK_HTTP_ERROR_TYPE_TIMEOUT  = -1001,
    INAPPSDK_HTTP_ERROR_TYPE_UNSUPPORTEDURL = -1002,
    INAPPSDK_HTTP_ERROR_TYPE_CANNOTFINDHOST = -1003,
    INAPPSDK_HTTP_ERROR_TYPE_CANNOTCONNECTTOHOST    = -1004,
    INAPPSDK_HTTP_ERROR_TYPE_NETWORKCONNECTIONLOST  = -1005,
    INAPPSDK_HTTP_ERROR_TYPE_DNSLOOKUPFAILED        = -1006,
    INAPPSDK_HTTP_ERROR_TYPE_HTTPTOOMANYREDIRECTS   = -1007,
    INAPPSDK_HTTP_ERROR_TYPE_RESOURCEUNAVAILABLE    = -1008,
    INAPPSDK_HTTP_ERROR_TYPE_NOTCONNECTEDTOINTERNET = -1009
    
} InAppSDKHTTPErrorType;


@interface InAppSDKHttpConnectionError : InAppSDKError

@end
